{{- if or .Values.envConfig .Values.fileConfig -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cron-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cron-chart.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.envConfig | nindent 2 }}
  {{- toYaml .Values.fileConfig | nindent 2 }}
{{- end }}

---


